"""baseline: mines, alert_logs, users

Revision ID: 0001_baseline
Revises:
Create Date: 2026-08-20 00:00:00 UTC

This is written by hand rather than autogenerated so the emitted DDL
stays deterministic across SQLAlchemy versions and doesn't depend on
whichever database the developer happens to have configured when they
run ``alembic revision --autogenerate``. Every future migration can
autogenerate from here.

Order of creation matters:

1. ``mines`` -- no FKs.
2. ``alert_logs`` and ``users`` -- both FK into ``mines``.
3. Indexes -- created inline for portability across SQLite (which
   inlines index definitions in the CREATE TABLE) and Postgres.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "mines",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("company", sa.String(length=120), nullable=False),
        sa.Column("location_name", sa.String(length=500), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("pit_depth_m", sa.Float(), nullable=False, server_default="150.0"),
        sa.Column("slope_angle_deg", sa.Float(), nullable=False, server_default="45.0"),
        sa.Column("contact_email", sa.String(length=320), nullable=True),
        sa.Column("contact_phone", sa.String(length=32), nullable=True),
        sa.Column(
            "alert_threshold_pct", sa.Float(), nullable=False, server_default="70.0"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.UniqueConstraint("name", name="ux_mines_name"),
    )

    op.create_table(
        "alert_logs",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("mine_id", sa.Integer(), nullable=False),
        sa.Column("risk_percentage", sa.Float(), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("rainfall_mm", sa.Float(), nullable=True),
        sa.Column("pore_pressure_kpa", sa.Float(), nullable=True),
        sa.Column("velocity_mm_h", sa.Float(), nullable=True),
        sa.Column("seismic_rms_g", sa.Float(), nullable=True),
        sa.Column("top_shap_reason", sa.Text(), nullable=True),
        sa.Column(
            "triggered_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.ForeignKeyConstraint(
            ["mine_id"],
            ["mines.id"],
            ondelete="CASCADE",
            name="fk_alert_logs_mine_id",
        ),
    )
    # Composite index matching get_recent_alerts's access pattern:
    # WHERE mine_id = ? ORDER BY triggered_at DESC LIMIT N.
    # Without it, every alert-history read is a full scan.
    op.create_index(
        "ix_alert_logs_mine_triggered",
        "alert_logs",
        ["mine_id", sa.text("triggered_at DESC")],
    )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("mine_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.ForeignKeyConstraint(
            ["mine_id"],
            ["mines.id"],
            ondelete="SET NULL",
            name="fk_users_mine_id",
        ),
        sa.UniqueConstraint("username", name="ux_users_username"),
    )


def downgrade() -> None:
    # Reverse order: alert_logs & users first (they FK into mines).
    op.drop_index("ix_alert_logs_mine_triggered", table_name="alert_logs")
    op.drop_table("users")
    op.drop_table("alert_logs")
    op.drop_table("mines")
